### ISSUE TITLE
Tracking key points for v2 documentation

### ISSUE THREAD

**Issue by dorranh** [tweag/funflow2#39]
This is a sort of FAQ list of general points mentioned in https://github.com/tweag/funflow2/pull/29 that we should make sure are addressed in the v2 documentation, some of which may already be written:

- [x] How are file inputs and outputs treated? (i.e. CS.Item)
- [x] How do I add a file to the content store?
- [x] What are placeholder / templated arguments for DockerEffects and what are their main benefits?
- [x] What kinds of outputs can I create using a DockerEffect (files) and at what path should they be saved?
- [x] How do I set up logging for my DockerEffects (i.e. via OutputCapture)?

**Comment by dorranh** [comment]
Closing since these points have been addressed in the docs.
