### ISSUE TITLE
Tracking: Release Prep

### ISSUE THREAD

**Issue by dorranh** [tweag/funflow2#81]
This issue is for tracking the steps required to get funflow2 ready for release (and repo migration)

- [x] Add aliases for common funflow functions (stepIO, etc.)
- [x] merge repos s.t. history is preserved
- [x] Label external-executor as unused in README (once repos are merged)
- [x] Write migration guide. Recreate key examples from funflow repo (related: #80)
- [x] Review funflow issue tracker to see if any can be easily addressed using the new version (mostly addressed as of #82)
